### ISSUE TITLE
docker repo does not exist

### ISSUE THREAD

**Issue by 0ro8lu** [aiim-research/GRETEL#2]
Hello, just wanted to let you know the docker repo you mention in the installation step does not seem to exist. not only does it not show up on docker hub, but trying to pull it from the CLI results in the following error message: 

_Error response from daemon: pull access denied for gretel/gretel, repository does not exist or may require 'docker login': denied: requested access to the resource is denied_

and yes, before you ask, I've successfully logged in using docker login before issuing the command.

**Comment by giovanni-stilo** [comment]
@0ro8lu Yes, thank you. The docker is not updated at the moment. We updated the README shortly for the moment. More info and the new docker image will come in the future.
