### ISSUE TITLE
Possible error in IRandExplainer

### ISSUE THREAD

**Issue by Davide-F5-Marincione** [aiim-research/GRETEL#3]
Good morning,
I was about to test this explainer but found the following fallacy in the code: since the explainer drops and adds edges at random, the edge weights should too be added or dropped by the explainer... right? If that makes sense; then the code doesn't do so! And, indeed this leads to inference errors when running the produced counterfactual in the oracle.

I propose to solve this by a simple fix: substitute https://github.com/aiim-research/GRETEL/blob/9489035edaa886ee2e62ee9a9066be6408b96e58/src/explainer/search/i_rand.py#L54-L56
with
```python
result = GraphInstance(instance.id, label=instance.label, data=cf_cand_matrix, node_features=instance.node_features)
```

Hopefully this makes sense, have a good day,
solaire_of_astora

**Comment by giovanni-stilo** [comment]
I think it was already solved in the meanwhile by  @MarioTheOne .
Please double check it and close it in case it is solved.

Thanks @Davide-F5-Marincione

**Comment by Davide-F5-Marincione** [comment]
The problem was solved, thanks!
